import type { LocationProfile, WaterSource } from './dataModels';

const seqGuidance: WaterSource = { title: 'Seqwater water quality reports', url: 'https://www.seqwater.com.au/water-quality-report', sourceType: 'pdf_report', humanLabel: 'Official water authority report', publisher: 'Seqwater', publicationDate: '2026-03-31', lastChecked: '2026-05-09', coverageLevel: 'Water authority', confidence: 'Medium' };
const qldHealth: WaterSource = { title: 'Queensland Health drinking water guidance', url: 'https://www.health.qld.gov.au/public-health/industry-environment/environment-land-water/water/quality/drinking', sourceType: 'guideline', humanLabel: 'Government drinking water guidance', publisher: 'Queensland Health', publicationDate: '2025-01-01', lastChecked: '2026-05-09', coverageLevel: 'State guidance', confidence: 'High' };
const reviewSource: WaterSource = { title: 'Regional dataset pending publication QA', sourceType: 'under_review', humanLabel: 'Source under review', publisher: 'Internal QA log from uploaded official records', lastChecked: '2026-05-09', coverageLevel: 'Regional', confidence: 'Low' };

const base = (p: Partial<LocationProfile>): LocationProfile => ({
  id: '', suburb: '', postcode: '', state: 'QLD', region: 'SE QLD', slug: '', aliases: [], providerName: '', waterAuthority: '', waterSourceContext: '', supplyContext: '', treatmentContext: '', disinfectantContext: '',
  hardnessCategory: 'Regional category under review', scaleRiskCategory: 'Property dependent', tasteOdourCategory: 'Property dependent', skinHairComfortCategory: 'Property dependent', applianceProtectionCategory: 'Property dependent', sedimentRustCategory: 'Property dependent',
  householdComfortWatchlist: [], whatToTestAtHome: ['Free/total chlorine', 'Hardness', 'pH', 'TDS', 'Sediment/turbidity', 'Taste and odour notes', 'Property plumbing factors'], recommendedFiltrationPathways: ['Chlorine taste/smell → catalytic carbon / carbon block', 'Sediment/rust → sediment pre-filtration', 'Scale/spotting → scale conditioning after testing', 'Whole-home comfort → whole-home filtration assessment'], commonLocalConcerns: [], confidence: 'Low', coverageLevel: 'Regional', freshness: 'Monthly', reviewStatus: 'Region-backed', lastChecked: '2026-05-09', sources: [seqGuidance, qldHealth], jilaEligible: true, seoIndexable: true, ...p
});

export const locationProfiles: LocationProfile[] = [
  base({ id:'brisbane-4000', suburb:'Brisbane CBD', postcode:'4000', slug:'brisbane-4000', aliases:['brisbane','brisbane cbd'], providerName:'Urban Utilities', waterAuthority:'Seqwater / Urban Utilities', waterSourceContext:'Supplied through the SEQ bulk water network with treated mains delivery.', supplyContext:'Supply can vary by zone and demand conditions.', treatmentContext:'Public mains treatment is managed to Australian requirements.', disinfectantContext:'Disinfectant approach can vary by network conditions and timing.', hardnessCategory:'Moderate (regional context)', scaleRiskCategory:'Medium', tasteOdourCategory:'Medium', skinHairComfortCategory:'Property dependent', applianceProtectionCategory:'Medium', sedimentRustCategory:'Low to property dependent', householdComfortWatchlist:['Chlorine taste/smell can be noticed at times.','Scale spotting can appear on fixtures depending on household conditions.','Taste can shift after weather events or network operations.'], commonLocalConcerns:['Taste & odour variation','Scale spotting','Skin/hair comfort'], confidence:'Medium', coverageLevel:'Water authority', reviewStatus:'Reviewed' }),
  base({ id:'south-brisbane-4101', suburb:'South Brisbane', postcode:'4101', slug:'south-brisbane-4101', aliases:['south brisbane'], providerName:'Urban Utilities', waterAuthority:'Seqwater / Urban Utilities', waterSourceContext:'Likely supplied from SEQ treated network serving Brisbane zones.', supplyContext:'Local streets can sit on different supply paths over time.', treatmentContext:'Treated mains water with source and treatment changes by zone/time.', disinfectantContext:'Disinfectant context available at authority level, not property exact.', scaleRiskCategory:'Medium', tasteOdourCategory:'Medium', commonLocalConcerns:['Chlorine taste','Apartment plumbing influence','Scale spotting'], confidence:'Medium', coverageLevel:'Water authority', reviewStatus:'Reviewed' }),
  base({ id:'west-end-4101', suburb:'West End', postcode:'4101', slug:'west-end-4101', aliases:['west end'], providerName:'Urban Utilities', waterAuthority:'Seqwater / Urban Utilities', waterSourceContext:'SEQ network treated mains for inner Brisbane.', supplyContext:'Older properties can experience plumbing-driven taste/metallic notes.', treatmentContext:'Authority treatment data available; property variation remains.', disinfectantContext:'Disinfectant context is network-level.', scaleRiskCategory:'Medium', tasteOdourCategory:'Medium', sedimentRustCategory:'Property dependent', confidence:'Medium', coverageLevel:'Water authority', reviewStatus:'Reviewed' }),
  base({ id:'caboolture-4510', suburb:'Caboolture', postcode:'4510', slug:'caboolture-4510', aliases:['moreton bay','caboolture'], providerName:'Unitywater', waterAuthority:'Seqwater / Unitywater', waterSourceContext:'Moreton Bay area treated mains connected to SEQ bulk supplies.', supplyContext:'Experience can vary by street plumbing and local works.', treatmentContext:'Treatment follows public authority standards.', disinfectantContext:'Disinfectant details are authority-level context.', scaleRiskCategory:'Medium', tasteOdourCategory:'Property dependent', sedimentRustCategory:'Medium', householdComfortWatchlist:['Sediment can be noticed after infrastructure works.','Taste changes can be short-term and local.'], confidence:'Medium', coverageLevel:'Water authority', reviewStatus:'Reviewed' }),
  base({ id:'ipswich-4305', suburb:'Ipswich', postcode:'4305', slug:'ipswich-4305', aliases:['ipswich'], providerName:'Local network provider', waterAuthority:'SEQ regional authorities', reviewStatus:'Being reviewed', confidence:'Low', seoIndexable:false, sources:[qldHealth, reviewSource] }),
  base({ id:'gold-coast-4215', suburb:'Gold Coast', postcode:'4215', slug:'gold-coast-4215', aliases:['southport','gold coast'], providerName:'Gold Coast Water', waterAuthority:'Seqwater / local retail network', reviewStatus:'Being reviewed', confidence:'Low', seoIndexable:false, sources:[qldHealth, reviewSource] }),
];

export const reviewedChips = ['Brisbane', 'South Brisbane 4101', 'West End 4101', 'Caboolture 4510', 'Ipswich', 'Gold Coast'];
