import type { LocationProfile, WaterSource, WatchItem } from './dataModels';

const seqGuidance: WaterSource = { title: 'SEQ water quality reports', url: 'https://www.seqwater.com.au/water-quality-report', sourceType: 'pdf_report', humanLabel: 'Official water authority report', publisher: 'Seqwater', publicationDate: '2026-03-31', lastChecked: '2026-05-09', coverageLevel: 'Water authority', confidence: 'Medium' };
const qldHealth: WaterSource = { title: 'Queensland Health drinking water guidance', url: 'https://www.health.qld.gov.au/public-health/industry-environment/environment-land-water/water/quality/drinking', sourceType: 'guideline', humanLabel: 'Government drinking water guidance', publisher: 'Queensland Health', publicationDate: '2025-01-01', lastChecked: '2026-05-09', coverageLevel: 'State guidance', confidence: 'High' };
const reviewSource: WaterSource = { title: 'Regional source review in progress', sourceType: 'under_review', humanLabel: 'Source under review', publisher: 'Review queue from public records', lastChecked: '2026-05-09', coverageLevel: 'Regional', confidence: 'Low' };

const watch = (items: Array<[string, WatchItem['level'], string]>): WatchItem[] => items.map(([label, level, note]) => ({ label, level, note }));

const base = (p: Partial<LocationProfile>): LocationProfile => ({
  id: '', suburb: '', postcode: '', state: 'QLD', region: 'SE QLD', slug: '', aliases: [], providerName: '', waterAuthority: '', waterSourceContext: '', supplyContext: '', treatmentContext: '', disinfectantContext: '',
  hardnessCategory: 'Regional context', scaleRiskCategory: 'Property dependent', tasteOdourCategory: 'Property dependent',
  householdComfortWatchlist: watch([['Taste & odour', 'Property dependent', 'This can vary by building plumbing and network timing.'],['Scale spotting', 'Property dependent', 'Spotting can vary by appliance and usage.'],['Skin & hair comfort', 'Property dependent', 'Comfort experience is personal and plumbing-dependent.'],['Appliance protection', 'Property dependent', 'Appliance scale impact can vary by property conditions.'],['Sediment/rust', 'Property dependent', 'Sediment can reflect local pipe age or nearby works.'],['Plumbing variation', 'Property dependent', 'Street and building plumbing can change your tap experience.']]),
  whatLocalsMayNotice: ['Chlorine taste or smell at times', 'Dry skin or hair after showering', 'White spots on glass/screens', 'Sediment or rust from older pipework', 'Earthy taste after weather changes', 'Appliance wear concerns'],
  whatToTestAtHome: ['Chlorine/chloramine', 'Hardness', 'pH', 'TDS', 'Sediment/turbidity', 'Taste/odour notes', 'Plumbing age and pipe material'],
  recommendedFiltrationPathways: ['Chlorine taste/smell → catalytic carbon / carbon block', 'Sediment/rust → sediment pre-filtration', 'Scale/spotting → scale management / conditioning', 'Whole-home comfort → whole-home filtration assessment', 'Fluoride concern → separate fluoride-specific review only'],
  confidence: 'Low', coverageLevel: 'Regional', freshness: 'Monthly', reviewStatus: 'Region-backed', lastChecked: '2026-05-09', sources: [seqGuidance, qldHealth], jilaEligible: true, seoIndexable: true,
  shareSummary: '', socialPost: '', ...p,
});

export const locationProfiles: LocationProfile[] = [
  base({ id: 'brisbane-4000', suburb: 'Brisbane CBD', postcode: '4000', slug: 'brisbane-4000', aliases: ['brisbane', 'brisbane cbd', 'city'], providerName: 'Urban Utilities', waterAuthority: 'Seqwater / Urban Utilities', waterSourceContext: 'Source-backed regional guidance from SEQ authority records for central Brisbane network areas.', supplyContext: 'Central Brisbane can be supplied through different SEQ paths during operational changes.', treatmentContext: 'Authority-managed treatment is applied before distribution to the metro network.', disinfectantContext: 'Disinfectant context is available at authority level and can vary by time and point in network.', hardnessCategory: 'Moderate regional category', scaleRiskCategory: 'Medium', tasteOdourCategory: 'Medium', confidence: 'Medium', coverageLevel: 'Water authority', reviewStatus: 'Reviewed', shareSummary: 'Brisbane CBD snapshot shows source-backed SEQ authority guidance for treatment context, taste/odour watchlist and home testing priorities.', socialPost: 'I checked the tap-water snapshot for Brisbane CBD. It shows source-backed regional guidance for taste, odour, scale comfort and what to test at your own tap. Worth checking your suburb.' }),
  base({ id: 'south-brisbane-4101', suburb: 'South Brisbane', postcode: '4101', slug: 'south-brisbane-4101', aliases: ['south brisbane'], providerName: 'Urban Utilities', waterAuthority: 'Seqwater / Urban Utilities', waterSourceContext: 'Source-backed profile using SEQ authority and regional treatment context for South Brisbane.', supplyContext: '4101 can share postcode with nearby suburbs and supply routing can vary locally.', treatmentContext: 'Network-level treatment context is available from authority records.', disinfectantContext: 'Disinfectant details are authority-level, not property-exact.', scaleRiskCategory: 'Medium', tasteOdourCategory: 'Medium', confidence: 'Medium', coverageLevel: 'Water authority', reviewStatus: 'Reviewed', shareSummary: 'South Brisbane profile summarises likely provider, treatment context and comfort watchlist guidance backed by authority-level records.', socialPost: 'I checked the South Brisbane tap-water snapshot. It gives source-backed guidance on taste, odour, scale comfort and what to test at home.' }),
  base({ id: 'west-end-4101', suburb: 'West End', postcode: '4101', slug: 'west-end-4101', aliases: ['west end'], providerName: 'Urban Utilities', waterAuthority: 'Seqwater / Urban Utilities', waterSourceContext: 'Source-backed regional guidance for West End within SEQ metro supply context.', supplyContext: 'Postcode 4101 has multiple suburbs, so profile stays suburb-specific where possible.', treatmentContext: 'Treatment context is authority-level with property-level variation possible.', disinfectantContext: 'Disinfectant context may vary by operational timing.', scaleRiskCategory: 'Medium', tasteOdourCategory: 'Medium', confidence: 'Medium', coverageLevel: 'Water authority', reviewStatus: 'Reviewed', shareSummary: 'West End snapshot highlights source-backed treatment context, comfort watchlist and practical testing checklist.', socialPost: 'I checked the West End tap-water snapshot. Useful suburb-level guidance for taste/odour, scale comfort and home testing.' }),
  base({ id: 'caboolture-4510', suburb: 'Caboolture', postcode: '4510', slug: 'caboolture-4510', aliases: ['caboolture', 'moreton bay'], providerName: 'Unitywater', waterAuthority: 'Seqwater / Unitywater', waterSourceContext: 'Source-backed regional profile for Caboolture/Moreton Bay mains context.', supplyContext: 'Local works and property plumbing can influence what households notice at the tap.', treatmentContext: 'Public treatment context from authority records is applied before distribution.', disinfectantContext: 'Disinfectant approach is network-managed and can vary in-system.', scaleRiskCategory: 'Medium', tasteOdourCategory: 'Property dependent', confidence: 'Medium', coverageLevel: 'Water authority', reviewStatus: 'Reviewed', shareSummary: 'Caboolture snapshot gives source-backed guidance for taste and scale watchlists, local notice patterns and what to test at home.', socialPost: 'I checked the tap-water snapshot for Caboolture. It shows source-backed regional guidance for taste, odour, scale comfort and what to test at your own tap. Worth checking your suburb.' }),
  base({ id: 'ipswich-4305', suburb: 'Ipswich', postcode: '4305', slug: 'ipswich-4305', aliases: ['ipswich'], providerName: 'Regional provider context', waterAuthority: 'SEQ regional authorities', confidence: 'Low', reviewStatus: 'Being reviewed', seoIndexable: false, sources: [qldHealth, reviewSource], shareSummary: 'Ipswich snapshot is a region-backed guidance profile while source review is in progress.', socialPost: 'I checked the Ipswich tap-water snapshot. It currently provides region-backed guidance plus what to test at home while review continues.' }),
  base({ id: 'gold-coast-4215', suburb: 'Gold Coast', postcode: '4215', slug: 'gold-coast-4215', aliases: ['gold coast', 'southport'], providerName: 'Gold Coast network context', waterAuthority: 'Seqwater / local retail network', confidence: 'Low', reviewStatus: 'Being reviewed', seoIndexable: false, sources: [qldHealth, reviewSource], shareSummary: 'Gold Coast snapshot offers guidance-tier context with confidence labels during source review.', socialPost: 'I checked the Gold Coast tap-water snapshot. It gives region-backed guidance for comfort watchlists and at-home testing.' }),
  base({ id: 'nundah-4012', suburb: 'Nundah', postcode: '4012', slug: 'nundah-4012', aliases: ['nundah', 'north brisbane'], providerName: 'Urban Utilities', waterAuthority: 'Seqwater / Urban Utilities', confidence: 'Low', reviewStatus: 'Being reviewed', seoIndexable: false, sources: [qldHealth, reviewSource], shareSummary: 'Nundah profile provides north-Brisbane guidance while suburb review completes.', socialPost: 'I checked the Nundah tap-water snapshot. It gives source-backed regional guidance and a practical home testing checklist.' }),
  base({ id: 'logan-4114', suburb: 'Logan', postcode: '4114', slug: 'logan-4114', aliases: ['logan'] , providerName:'SEQ provider context', waterAuthority:'SEQ regional authorities', confidence:'Low', reviewStatus:'Being reviewed', seoIndexable:false, sources:[qldHealth, reviewSource], shareSummary:'Logan guidance profile available while review continues.', socialPost:'I checked Logan guidance on the tap-water lookup tool.'}),
  base({ id: 'redlands-4165', suburb: 'Redlands / Bayside', postcode: '4165', slug: 'redlands-bayside-4165', aliases: ['redlands','bayside'], providerName:'SEQ provider context', waterAuthority:'SEQ regional authorities', confidence:'Low', reviewStatus:'Being reviewed', seoIndexable:false, sources:[qldHealth, reviewSource], shareSummary:'Redlands/Bayside profile currently provides guidance-tier context.', socialPost:'I checked the Redlands/Bayside tap-water snapshot for comfort watchlist guidance.'}),
  base({ id: 'sunshine-coast-4558', suburb: 'Sunshine Coast', postcode: '4558', slug: 'sunshine-coast-4558', aliases: ['sunshine coast'], providerName:'Regional provider context', waterAuthority:'SEQ regional authorities', confidence:'Low', reviewStatus:'Being reviewed', seoIndexable:false, sources:[qldHealth, reviewSource], shareSummary:'Sunshine Coast profile provides guidance and testing checklist while review is underway.', socialPost:'I checked the Sunshine Coast tap-water guidance snapshot.'}),
];

export const reviewedChips = ['Brisbane', 'South Brisbane', 'West End', 'Caboolture', 'Ipswich', 'Gold Coast', 'Nundah'];
